### PR TITLE
Fix queries and response packets content for undelegated tests

### LINKED ISSUE #1100: Is cached data handled incorrectly when processing an undelegated test?
While investigating #1099 I ran the following command:

```
zonemaster-cli 190.187.193.in-addr.arpa --ns ns1.oxilion.nl --ns ns2.oxilion.nl --ns ns3.oxilion.net --raw --level debug3 --test dnssec/dnssec11 > debug-dnssec11
```
I looked for DS queries and found some, for example the following. Note that it says that all flags are unset. Is that really correct? We expect both AA flag and QR flag to be set. We do not expect a referral.
```
   0.35 DEBUG2    DNSSEC11       FAKE_DELEGATION   class=IN; from=ns3.afrinic.net/2001:500:14:6100:ad::1; name=190.187.193.in-addr.arpa; type=DS
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN   packet=;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 0
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; flags: ; QUERY: 1, ANSWER: 0, AUTHORITY: 3, ADDITIONAL: 6
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; QUESTION SECTION:
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; 190.187.193.in-addr.arpa.     IN      DS
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN>
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; ANSWER SECTION:
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN>
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; AUTHORITY SECTION:
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> 190.187.193.in-addr.arpa.        3600    IN      NS      ns2.oxilion.nl.
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> 190.187.193.in-addr.arpa.        3600    IN      NS      ns3.oxilion.net.
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> 190.187.193.in-addr.arpa.        3600    IN      NS      ns1.oxilion.nl.
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN>
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; ADDITIONAL SECTION:
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns2.oxilion.nl.  3600    IN      AAAA    2a00:d10:3::53:2
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns2.oxilion.nl.  3600    IN      A       93.186.184.50
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns3.oxilion.net. 3600    IN      AAAA    2001:898:2000:1000::5
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns3.oxilion.net. 3600    IN      A       213.206.97.203
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns1.oxilion.nl.  3600    IN      AAAA    2a00:d10::53:1
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ns1.oxilion.nl.  3600    IN      A       93.186.179.180
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN>
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; Query time: 0 msec
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; EDNS: version 0; flags: do ; udp: 0
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; SERVER: 2001:500:14:6100:ad::1
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; WHEN: Thu Jan  1 00:00:00 1970
   0.35 DEBUG2    DNSSEC11       FAKED_RETURN> ;; MSG SIZE  rcvd: 0
```

Compare the response when a query is sent by dig() to the same IP address. Both AA and QR flags are set. It is not a referral.
```
; <<>> DiG 9.18.2 <<>> @2001:500:14:6100:ad::1 190.187.193.in-addr.arpa DS +dnssec +multiline +norecurse
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3229
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
; COOKIE: 03862066f168f2fe0159dfef62d7e74f7fe34edb39665c18 (good)
;; QUESTION SECTION:
;190.187.193.in-addr.arpa. IN DS

;; AUTHORITY SECTION:
193.in-addr.arpa.	3600 IN	SOA pri.authdns.ripe.net. dns.ripe.net. (
				1658311974 ; serial
				3600       ; refresh (1 hour)
				600        ; retry (10 minutes)
				864000     ; expire (1 week 3 days)
				3600       ; minimum (1 hour)
				)
193.in-addr.arpa.	3600 IN	RRSIG SOA 13 3 3600 (
				20220803101254 20220720084254 58688 193.in-addr.arpa.
				2RpHztqCB1Eh/FuC2Jc/qlUpQ47zENxWi0XsR6MUHoQL
				OapcVFyhQQ4CBSf5S5U+ynIAvhmz9S+VQgkxQB2kRQ== )
190.187.193.in-addr.arpa. 3600 IN NSEC 196.187.193.in-addr.arpa. NS RRSIG NSEC
190.187.193.in-addr.arpa. 3600 IN RRSIG	NSEC 13 5 3600 (
				20220803101254 20220720084254 58688 193.in-addr.arpa.
				+tOkYDO6U+OhMDHtBTPnLLast7RmA6kcdxA/C26st+JU
				KS2NLDHux7366OoUePKOoq6wM55hEXFbASFPKpmZng== )

;; Query time: 11 msec
;; SERVER: 2001:500:14:6100:ad::1#53(2001:500:14:6100:ad::1) (UDP)
;; WHEN: Wed Jul 20 11:30:23 UTC 2022
;; MSG SIZE  rcvd: 435
```

### PR DESCRIPTION
**Pull request by tgreenx**
## Purpose

For undelegated tests (fake delegation), this PR adds the QR flag in queries and AA flag depending if DS record is provided or not.

## Context

Fixes #1100 

## Changes

- Sets the QR flag for queries in undelegated tests
- Sets the AA flag for queries in undelegated tests with DS record
- Returns empty sections in response packet to a DS query in undelegated tests with no DS record

## How to test this PR

`
zonemaster-cli 190.187.193.in-addr.arpa --ns ns1.oxilion.nl --ns ns2.oxilion.nl --ns ns3.oxilion.net --raw --level debug3 --test dnssec/dnssec11  > debug-dnssec11`

Inspect debug file `debug-dnssec11`. Search for `type=DS`. Look at flags and packet content thereafter. You can change query type in dnssec11 and compare.

### CODE REVIEW

File: lib/Zonemaster/Engine/Nameserver.pm [hunk 1]
```diff
@@ -269,16 +273,21 @@ sub query {
                 $p->unique_push( 'answer',     $_ ) for @{$name};
                 $p->unique_push( 'additional', $_ ) for @{$addr};
             }
+            elsif ( $type eq 'DS' ) {
+                $p->aa( 1 );
+            }
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Nameserver.pm:278]: Will type DS ever come here? This is an iteration around fake_delegation and that includes the name servers only, doesn't it?

**Comment by matsduf** [comment]
> Inspect debug file `debug-dnssec11`. Search for `type=DS`. Look at flags and packet content thereafter. You can change query type in dnssec11 and compare.

How can you change the query type when running a test case?

File: lib/Zonemaster/Engine/Nameserver.pm (hunk 1 above)
Comment (tgreenx) [reply lib/Zonemaster/Engine/Nameserver.pm:278]: Yes it will come here for DS queries in undelegated tests without DS record provided.

**Comment by tgreenx** [comment]
> > Inspect debug file `debug-dnssec11`. Search for `type=DS`. Look at flags and packet content thereafter. You can change query type in dnssec11 and compare.
> 
> How can you change the query type when running a test case?

You change query type directly in the code of the Test Case, for example [here](https://github.com/zonemaster/zonemaster-engine/blob/develop/lib/Zonemaster/Engine/Test/DNSSEC.pm#L2859). And just add `die;` right after to abort the test early, it is enough for our purpose.

```
my $ds_p = $ns->query( $zone->name, q{SOA}, { dnssec => 1, usevc => 0 } );
die;
```

**Comment by tgreenx** [comment]
@matsduf please re-review

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
The "How to test" does not work. In undelegated test there is no DS query for DNSSEC11. The following command works better:
```
zonemaster-cli 190.187.193.in-addr.arpa --ns ns1.oxilion.nl --ns ns2.oxilion.nl --ns ns3.oxilion.net --raw --level debug3 --test dnssec/dnssec02 > debug-dnssec02
```

**Comment by matsduf** [comment]
The result looks strange, but it probably does not affect the end result of Zonemaster. Issue #1169 has been created.
