### PR TITLE
- Fixes zonemaster/zonemaster-engine#584

### LINKED ISSUE #584: Implement DNSSEC14
PR zonemaster/zonemaster#783 created a new test case, [DNSSEC14], which is to be implemented by this issue.

[DNSSEC14]: https://github.com/zonemaster/zonemaster/blob/develop/docs/specifications/tests/DNSSEC-TP/dnssec14.md

### PR DESCRIPTION
**Pull request by vlevigneron**
- Implement DNSSEC14
- Translation is coming...

Resolves #584

### CODE REVIEW

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 1]
```diff
@@ -344,6 +375,16 @@ sub metadata {
...
         ],
+        dnssec14 => [
+            qw(
+              NO_RESPONSE
+              NO_RESPONSE_DNSKEY
+	      DNSKEY_SMALLER_THAN_REC
+	      DNSKEY_TOO_SMALL_FOR_ALGO
+	      DNSKEY_TOO_LARGE_FOR_ALGO
+	      KEY_SIZE_OK
+              ),
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm]: Uneven indentation.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 2]
```diff
@@ -1460,6 +1513,82 @@ sub dnssec11 {
...
+
+    for my $key ( sort keys %nss ) {
+        my $ns = $nss{$key};
+        my $ns_args = {
+            ns      => $ns->name->string,
+            address => $ns->address->short,
+        };
+
+	if ( not Zonemaster::Engine::Profile->effective->get(q{net.ipv4}) and $ns->address->version == $IP_VERSION_4 ) {
+            Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns => "$ns" } );
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm]: IPV4_DISABLED, to be consistent with other modules.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 3]
```diff
@@ -1460,6 +1513,82 @@ sub dnssec11 {
...
+            next;
+	}
+        if ( not Zonemaster::Engine::Profile->effective->get(q{net.ipv6}) and $ns->address->version == $IP_VERSION_6 ) {
+            Zonemaster::Engine->logger->add( SKIP_IPV6_DISABLED => { ns => "$ns" } );
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm]: IPV6_DISABLED, to be consistent with other modules.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 4]
```diff
@@ -1460,6 +1513,82 @@ sub dnssec11 {
...
+            push @results, info( DNSKEY_SMALLER_THAN_REC => $algo_args );
+        }
+
+        if ( $key->keysize > $rsa_key_size_details{$algo}{max_size} ) {
+            push @results, info( DNSKEY_TOO_LARGE_FOR_ALGO => $algo_args );
+        }
+
+    } ## end foreach my $key ( @keys )
+
+    if ( scalar @dnskey_rrs and not scalar @results ) {
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm]: Since NO_RESPONSE is added to `@results` the condition is not fully correct. From specification:
```
6. If *DNSKEY RRs* is non-empty and no messages, except for any
   *[NO_RESPONSE]*, has been outputted, then output 
   *[KEY_SIZE_OK]*.      
```

File: lib/Zonemaster/Engine/Test/DNSSEC.pm (hunk 2 above)
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: OK, could you review  https://github.com/zonemaster/zonemaster-engine/pull/587 before. This is the same concern and it should be easier to merge.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm (hunk 4 above)
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Fixed in https://github.com/zonemaster/zonemaster-engine/pull/586/commits/e6d5987a539f39e3840ec0ff355e19860b319c1f

File: lib/Zonemaster/Engine/Test/DNSSEC.pm (hunk 1 above)
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Fixed in https://github.com/zonemaster/zonemaster-engine/pull/586/commits/e6d5987a539f39e3840ec0ff355e19860b319c1f

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 5]
```diff
@@ -1460,6 +1514,82 @@ sub dnssec11 {
...
 
+sub dnssec14 {
+    my ( $class, $zone ) = @_;
+    my @results;
+    my @dnskey_rrs;
+    my %dnskey_rrs;
+
+    my @nss_del   = @{ Zonemaster::Engine::TestMethods->method4( $zone ) };
+    my @nss_child = @{ Zonemaster::Engine::TestMethods->method5( $zone ) };
+    my %nss       = map { $_->name->string . '/' . $_->address->short => $_ } @nss_del, @nss_child;
```
Comment (mattias-p) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm]: Are you aware of the Zonemaster::Engine::Nameserver::string method? It's a shorter way to say the same thing.

Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Yes, but as dnssec14 skeleton is a cut/paste from dnssec05, I kept the same code. And I just want to add dnssec14 in this PR, not do re-factoring task or modifications in others dnssec* methods.

**Comment by matsduf** [comment]
Should this PR update one of the po files? All po files will be updated by #588.

**Comment by vlevigneron** [comment]
@matsduf Good question. There are some translation needs here. We can decide to wait for merge of  https://github.com/zonemaster/zonemaster-engine/pull/588, remove po file of this PR and create a new issue to do the translation after.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 6]
```diff
@@ -1460,6 +1514,82 @@ sub dnssec11 {
...
+        my $ns = $nss{$key};
+        my $ns_args = {
+            ns      => $ns->name->string,
+            address => $ns->address->short,
+        };
+
+	if ( not Zonemaster::Engine::Profile->effective->get(q{net.ipv4}) and $ns->address->version == $IP_VERSION_4 ) {
+            Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns => "$ns" } );
+            next;
+	}
```
[the remark this answers is not in the document]
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Fixed

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 7]
```diff
@@ -1460,6 +1514,82 @@ sub dnssec11 {
     return @results;
 } ## end sub dnssec11
 
+sub dnssec14 {
+    my ( $class, $zone ) = @_;
+    my @results;
+    my @dnskey_rrs;
+    my %dnskey_rrs;
```
[the remark this answers is not in the document]
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Fixed

**Comment by mattias-p** [comment]
The current documentation states that the programmer should update PO files. However I think there's a better way that we should adopt. I reread the translation documentation and came up with a couple of other thinks as well, so I created #594.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm (hunk 2 above)
Comment (vlevigneron) [reply lib/Zonemaster/Engine/Test/DNSSEC.pm]: Fixed in https://github.com/zonemaster/zonemaster-engine/pull/586/commits/bf1f3da5dea521c8b3015d83b958b64fca7a8632

**Comment by vlevigneron** [comment]
@matsduf can you approve it again ? There was a missing message preventing Travis to succeed. It has been fixed in the last commit.
