### PR TITLE
Make locale not get stuck on FreeBSD 11

### LINKED ISSUE #748: Translation language gets stuck on FreeBSD 11 (Engine)
Selecting language does not work correctly on FreeBSD 11. After you construct the Zonemaster::Engine::Translator instance and call $translator->locale() with a locale argument, the result is correctly translated to that language. However, if you keep making those calls the translation language argument is no longer respected. Instead locale get stuck on the value from a previous call. 

Fixing this should also fix zonemaster/zonemaster-backend#530.

### PR DESCRIPTION
**Pull request by mattias-p**
This makes Z::E::Translator properly communicate locale to gettext.

Fixes #748 and zonemaster/zonemaster-backend#530.

This PR is best reviewed commit by commit.

### CODE REVIEW

File: lib/Zonemaster/Engine/Translator.pm [hunk 1]
```diff
@@ -118,6 +119,11 @@ sub BUILD {
     my ( $self ) = @_;
 
     my $locale = $self->{locale} // _get_locale();
+
+    # Make sure LC_MESSAGES can be effectively set down the line.
+    delete $ENV{LANGUAGE};
```
Comment (mattias-p) [inline lib/Zonemaster/Engine/Translator.pm:124]: I'm having second thoughts on clearing LANGUAGE here. It makes it impossible to create applications that respect LANGUAGE in a clean way. I'll make an update to fix that.
