### PR TITLE
Fix DNSSEC10 for name servers sharing the same IPs

### LINKED ISSUE #1454: DNSSEC10 fails when multiple NS share the same IP address
A domain fails with DS10_EXPECTED_NSEC_NSEC3_MISSING: https://www.zonemaster.net/en/result/5ffb1feca8082fda

Nameserver(s) work(s) Ok. The problem might be that all nameservers for the domain share the same IP.

### PR DESCRIPTION
**Pull request by tgreenx**
## Purpose

This PR fixes a bug in DNSSEC10 where `DS10_EXPECTED_NSEC_NSEC3_MISSING` is wrongly outputted for name servers sharing the same IPs. For this type of name servers it should now also output, for all message tags, all name servers name/IP pairs.

## Context

Fixes #1454 
Updated test scenarios from https://github.com/zonemaster/zonemaster/pull/1383

## Changes

- Update implementation
- Update unit tests and data files

## How to test this PR

Unit tests are updated and should pass.

### CODE REVIEW

**Comment by matsduf** [comment]
Two more scenarios have been added in https://github.com/zonemaster/zonemaster/pull/1383, GOOD-NSEC-3 and GOOD-NSEC3-2. Both should output as e.g. GOOD-NSEC-1. Just as with GOOD-NSEC-2 and GOOD-NSEC3-2 there are extra names with the same IP, one name in delegation and the other in zone.

**Comment by matsduf** [comment]
> When testing the scenarios with this PR installed, the new scenarios pass, but is it correct?
> 
> ```
> $ zonemaster-cli --show-testcase --level INFO --test dnssec10 --hints ../../COMMON/hintfile --raw GOOD-NSEC-2.dnssec10.xa 
>    0.00 INFO     Unspecified    GLOBAL_VERSION  version=v7.1.0
>    0.07 INFO     DNSSEC10       DS10_HAS_NSEC  ns_list=ns1a.good-nsec-2.dnssec10.xa/127.15.10.31;ns1a.good-nsec-2.dnssec10.xa/fda1:b2:c3:0:127:15:10:31
> ```
> 
> The zone is delegated to three NS, ns1a, ns1b and ns1c, but only the first one is listed under DS10_HAS_NSEC. I expect all three to be listed.

This is a different bug compared to what this PR is to resolve. The bug in this comment will be lifted into an issue instead.

**Review by matsduf — DISMISSED** [review]
This is fine.

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 1]
```diff
@@ -3145,78 +3145,80 @@ sub dnssec10 {
     my ( @nsec_response_error, @nsec3param_response_error );
     my ( @with_dnskey, @without_dnskey );
 
-    my @nss = grep { $_->isa('Zonemaster::Engine::Nameserver') } (
+    my @nameservers = grep { $_->isa('Zonemaster::Engine::Nameserver') } (
                 @{ Zonemaster::Engine::TestMethodsV2->get_del_ns_names_and_ips( $zone ) // [] },
                 @{ Zonemaster::Engine::TestMethodsV2->get_zone_ns_names_and_ips( $zone ) // [] }
               );
```
Comment (mattias-p) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm:3151]:
```suggestion
    my @all_ns = uniq grep { $_->isa('Zonemaster::Engine::Nameserver') } (
                @{ Zonemaster::Engine::TestMethodsV2->get_del_ns_names_and_ips( $zone ) // [] },
                @{ Zonemaster::Engine::TestMethodsV2->get_zone_ns_names_and_ips( $zone ) // [] }
              );
```

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 2]
```diff
@@ -3145,78 +3145,80 @@ sub dnssec10 {
...
+
     my @ignored_nss;
+    my %nss;
+    push @{ $nss{$_->address->short} }, $_ for ( uniq @nameservers );
```
Comment (mattias-p) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm:3155]:
```suggestion
    push @{ $nss{$_->address->short} }, $_ for @all_ns;
```

File: lib/Zonemaster/Engine/Test/DNSSEC.pm [hunk 3]
```diff
@@ -3788,7 +3790,9 @@ sub dnssec10 {
           );
     }
 
-    $lc = List::Compare->new( [ @nss ], [ @ignored_nss, @without_dnskey, @nsec_in_answer, @nsec3param_nsec_nodata, @nsec3param_in_answer, @nsec_nsec3_nodata ] );
+    my @all_ns = map { $_ } ( map { @{ $_ } } values %nss );
+
```
Comment (mattias-p) [inline lib/Zonemaster/Engine/Test/DNSSEC.pm:3794]:
```suggestion
```

**Review by mattias-p — APPROVED** [review]
This looks reasonable to me. I believe I found a slightly simplifying refactoring.

**Comment by matsduf** [comment]
> > When testing the scenarios with this PR installed, the new scenarios pass, but is it correct?
> > ```
> > $ zonemaster-cli --show-testcase --level INFO --test dnssec10 --hints ../../COMMON/hintfile --raw GOOD-NSEC-2.dnssec10.xa 
> >    0.00 INFO     Unspecified    GLOBAL_VERSION  version=v7.1.0
> >    0.07 INFO     DNSSEC10       DS10_HAS_NSEC  ns_list=ns1a.good-nsec-2.dnssec10.xa/127.15.10.31;ns1a.good-nsec-2.dnssec10.xa/fda1:b2:c3:0:127:15:10:31
> > ```
> >   
> > The zone is delegated to three NS, ns1a, ns1b and ns1c, but only the first one is listed under DS10_HAS_NSEC. I expect all three to be listed.
> 
> This is a different bug compared to what this PR is to resolve. The bug in this comment will be lifted into an issue instead.

With https://github.com/zonemaster/zonemaster-engine/pull/1457/commits/7690d4ef20ad9a87de81f584a82d58179f53d074 I get a correct result with all NS listed.

**Review by matsduf — DISMISSED** [review]

**Review by mattias-p — APPROVED** [review]
