### PR TITLE
Profile fixes

### LINKED ISSUE #1355: Missing profile properties
When I run `zonemaster-cli --dump-profile` (using Zonemaster Engine 5.0.0) to print the default profile I get the following output:

```json
{
   "asn_db" : {
      "sources" : {
         "cymru" : [
            "asnlookup.zonemaster.net"
         ],
         "ripe" : [
            "riswhois.ripe.net"
         ]
      },
      "style" : "cymru"
   },
   "logfilter" : {},
   "net" : {
      "ipv4" : true,
      "ipv6" : true
   },
   "no_network" : false,
   "resolver" : {
      "defaults" : {
         "debug" : false,
         "fallback" : true,
         "igntc" : false,
         "recurse" : false,
         "retrans" : 3,
         "retry" : 2,
         "timeout" : 5,
         "usevc" : false
      }
   },
   "test_cases" : [
      ...
   ],
   "test_cases_vars" : {
      "dnssec04" : {
         "DURATION_LONG" : 15552000,
         "REMAINING_LONG" : 15552000,
         "REMAINING_SHORT" : 43200
      },
      "zone02" : {
         "SOA_REFRESH_MINIMUM_VALUE" : 14400
      },
      "zone04" : {
         "SOA_RETRY_MINIMUM_VALUE" : 3600
      },
      "zone05" : {
         "SOA_EXPIRE_MINIMUM_VALUE" : 604800
      },
      "zone06" : {
         "SOA_DEFAULT_TTL_MAXIMUM_VALUE" : 86400,
         "SOA_DEFAULT_TTL_MINIMUM_VALUE" : 300
      }
   },
   "test_levels" : {
      ...
   }
}
```

Comparing this to the [list of profile properties](https://metacpan.org/release/ZNMSTR/Zonemaster-Engine-v5.0.0/view/lib/Zonemaster/Engine/Profile.pm#PROFILE-PROPERTIES) we can see that these properties are not included in the output:

* asnroots
* cache
* resolver.source
* resolver.source4
* resolver.source6

The default profile should include all properties.

### PR DESCRIPTION
**Pull request by mattias-p**
## Purpose

The initial aim of this PR was to add some missing properties to the default profile. But in the process of making the update I discovered more problems with the profile and I'm including fixes for all of them here.

## Context

Fixes #1355.

Conflicts but is not blocked by #1257.

I marked this minor because of the new Zonemaster::Engine::Profile->all_properties method. Otherwise this would be V-Patch.

## Changes

* The default value for one property is specified:
  * `cache`
* The default values for some properties are implemented:
  * `asnroots`
  * `cache`
* Validation error messages are updated to state that the empty string is a valid value for some properties:
  * `resolver.source4`
  * `resolver.source6`
* Unit tests for invariants that cover all properties are updated to loop over the properties. Historically we tried and failed to include all properties in these tests.
  * 'new() returns a profile with all properties unset'
  * 'default() returns a profile with all properties set'
  * 'from_json("{}") returns a profile with all properties unset'
  * 'set() dies on attempts to unset properties'
* A new method is introduced to facilitate the improved unit testing:
  * Zonemaster::Engine::Profile->all_properties()

## How to test this PR

Run the unit tests.

### CODE REVIEW

File: lib/Zonemaster/Engine/Profile.pm [hunk 1]
```diff
@@ -83,28 +84,29 @@ my %profile_properties_details = (
     },
     q{resolver.source} => {
         type    => q{Str},
+        default => 'os_default',
         test    => sub {
-            if ( $_[0] ne $RESOLVER_SOURCE_OS_DEFAULT ) {
-                Net::IP::XS->new( $_[0] ) || $log->warning( "Property resolver.source must be an IP address or the exact string $RESOLVER_SOURCE_OS_DEFAULT" );
+            if ( $_[0] ne $RESOLVER_SOURCE_OS_DEFAULT and not Net::IP::XS->new( $_[0] ) ) {
+                die "Property resolver.source must be an IP address or the exact string $RESOLVER_SOURCE_OS_DEFAULT";
```
Comment (matsduf) [inline lib/Zonemaster/Engine/Profile.pm:90]: As far as I can see `Net::IP::XS->new( "10.0.1/24" )` is true.

**Comment by mattias-p** [comment]
> FYI this also conflicts with #1257 which removes the deprecated `asnroots` property.

True. I'd prefer if we could merge these two PRs in any order though, and whoever comes in second place gets to rebase. Is that okay with you?

**Review by MichaelTimbert — APPROVED** [review]
Good for me
